### ISSUE TITLE
Deploy named s3 buckets

### ISSUE THREAD

**Issue by BoKKeR** [jbesw/sar-s3-serverless-uploader#1]
Is there a way to deploy manually named s3 buckets? I tried changing the name in the template but it did not do anything. Cant really find much about it on the internet either.

**Comment by jbesw** [comment]
Yes - in the SAM template.yaml, where the S3 bucket is defined in the "Resources" section, simply add a BucketName property like this:

```
  S3UploadBucket:
    Type: AWS::S3::Bucket  
    Properties:
      BucketName: MyCustomBucketName
```

Additionally, if you want the bucket name to be a parameter during the deployment process, you can do this...

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: s3-uploader

Parameters:
  S3UploadBucketName:
    Type: String
    Default: 'MyCustomBucketName'

Resources:
  ## S3 buckets
  DocumentsBucket:
    Type: AWS::S3::Bucket  
    Properties:
      BucketName: !Ref S3UploadBucketName
```
HTH!
